name: thomasdargent.com Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-flask
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV
      - name: List files
        run: ls -R
      - name: Run python tests
        run: python -m pytest
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install Node.js dependencies
        run: npm install
      - name: Run Flask server and HTML accessibility tests
        run: |
          # Start the Flask server in the background
          python -m flask_app.app &
          SERVER_PID=$!  # Capture the server PID
          # Allow the server time to start
          sleep 5
          # Check if the server is running
          (curl -sSf http://127.0.0.1:5000 > /dev/null || {
            echo "Server failed to start";
            kill $SERVER_PID;
            exit 1;
          })
          # Run the first test and capture its exit code
          node tests/axe-core.test.js || EXIT_CODE=$?
          # Run the second test and update the exit code if necessary
          node tests/pa11y.test.js || EXIT_CODE=$EXIT_CODE || $?
          # Kill the Flask server
          (kill $SERVER_PID 2>/dev/null || echo "Server process already exited")
          # Exit with the final exit code
          exit ${EXIT_CODE:-0}
